"""Sensor platform — one SensorEntity per row in SENSOR_DESCRIPTIONS below.

Only rows this inverter type actually serves get an entity. sofar_modbus has no
public "what will this device poll" surface (it settles that privately in
async_setup()) — only what one poll actually attempted, via UpdateReport. Since
every attempted component lands in exactly one of `updated` or `failed`, their
union is the served set, and the coordinator's first refresh (already run by
the time this platform is set up — see __init__.py) gives us one for free.

Each entity is also available independently of the others: sofar_modbus reads
components one at a time and contains a failed one in the poll's UpdateReport
rather than failing the whole update, so only the entities on a component that
actually failed this poll go unavailable — not all of them.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from enum import IntEnum

from homeassistant.components.sensor import (
    RestoreSensor,
    SensorDeviceClass,
    SensorEntity,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import (
    PERCENTAGE,
    UnitOfApparentPower,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfReactivePower,
    UnitOfTemperature,
    UnitOfTime,
)
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity import EntityCategory
from homeassistant.helpers.entity_platform import AddEntitiesCallback

from .coordinator import SofarConfigEntry, SofarDataUpdateCoordinator
from .entity import SofarEntity

# GENERATOR: hand-written below, preserved verbatim by scripts/generate_sofar_model.py.


def _enum_label(member_name: str) -> str:
    """Must match scripts/generate_sofar_model.py's _enum_label — the label
    format used here and the `options` list declared on an ENUM sensor's
    description have to agree, or HA logs a state that isn't one of the
    declared options.
    """
    return " ".join(word.capitalize() for word in member_name.split("_"))


# How far below a total_increasing sensor's high-water mark a reading is still
# treated as read noise rather than a genuine reset. The two dips actually
# observed on this hardware (both on this integration and on solax_modbus
# reading the same inverter) were ~0.003% and ~0.0006% — a device-side torn
# read of a 32-bit counter split across two registers, not a comms failure.
# 1% leaves a wide margin above that noise while staying far below HA core's
# own reset_detected() threshold (drops below 90% of the previous value are
# treated as a meter reset — see homeassistant/components/sensor/recorder.py),
# so a genuine reset (e.g. a daily counter's midnight rollover to 0) still
# passes straight through untouched either way.
_TOTAL_INCREASING_DIP_TOLERANCE = 0.01


async def async_setup_entry(hass: HomeAssistant, entry: SofarConfigEntry, async_add_entities: AddEntitiesCallback) -> None:
    coordinator = entry.runtime_data
    report = coordinator.data
    served = report.updated | set(report.failed)

    entities = [
        (
            SofarTotalSensor
            if description.state_class in (SensorStateClass.TOTAL, SensorStateClass.TOTAL_INCREASING)
            else SofarSensor
        )(coordinator, description)
        for description in SENSOR_DESCRIPTIONS
        if description.component in served  # not served by this inverter type otherwise
    ]
    async_add_entities(entities)


class SofarSensor(SofarEntity, SensorEntity):
    """A read-only value off one of the device's Components."""

    entity_description: SofarSensorDescription

    def __init__(self, coordinator: SofarDataUpdateCoordinator, description: SofarSensorDescription) -> None:
        super().__init__(coordinator, description.key, description.component)
        self.entity_description = description

    @property
    def native_value(self) -> str | int | float | date | None:
        component = getattr(self.coordinator.device, self.entity_description.component)
        value = getattr(component, self.entity_description.key)
        # IntEnum.__str__ prints just the int since Python 3.11 (unlike plain
        # Enum) — translate to the label an ENUM-device-class sensor declared
        # in its `options`, rather than showing a bare number.
        if isinstance(value, IntEnum):
            return _enum_label(value.name)
        return value


class SofarTotalSensor(SofarEntity, RestoreSensor):
    """A long-term statistic: it holds its last value, and may outlive the device.

    Restored on startup so energy dashboard sensors never show `unknown`
    during the boot-up window or overnight, and so the dip guard's high-water
    mark anchors immediately rather than accepting a torn read on first poll.
    """

    entity_description: SofarSensorDescription

    def __init__(self, coordinator: SofarDataUpdateCoordinator, description: SofarSensorDescription) -> None:
        super().__init__(coordinator, description.key, description.component)
        self.entity_description = description
        self._total_increasing_high_water: float | None = None

    @property
    def available(self) -> bool:
        # Total and total_increasing counters hold available unconditionally
        # (even across link drops or offline nights) so long-term statistics
        # and the energy dashboard stay unbroken.
        return True

    async def async_added_to_hass(self) -> None:
        await super().async_added_to_hass()
        if (last_data := await self.async_get_last_sensor_data()) is not None:
            if last_data.native_value is not None:
                try:
                    val = float(str(last_data.native_value))
                    self._attr_native_value = val
                    self._total_increasing_high_water = val
                except (ValueError, TypeError):
                    pass

    @property
    def native_value(self) -> int | float | None:
        component = getattr(self.coordinator.device, self.entity_description.component)
        value = getattr(component, self.entity_description.key)
        if value is not None:
            if self.entity_description.state_class is SensorStateClass.TOTAL_INCREASING and isinstance(value, (int, float)):
                self._attr_native_value = self._smoothed_total_increasing(float(value))
            elif isinstance(value, (int, float)):
                self._attr_native_value = value
        if isinstance(self._attr_native_value, (int, float)):
            return self._attr_native_value
        return None

    def _smoothed_total_increasing(self, value: float) -> float:
        """Hold a total_increasing sensor at its high-water mark through a
        small dip (device-side torn read of a multi-register counter) instead
        of publishing a value HA would log as "not strictly increasing" — but
        let a genuine drop (a daily counter's midnight reset, an actual meter
        reset) through immediately. See _TOTAL_INCREASING_DIP_TOLERANCE.
        """
        high_water = self._total_increasing_high_water
        if high_water is None or value >= high_water or value < high_water * (1 - _TOTAL_INCREASING_DIP_TOLERANCE):
            self._total_increasing_high_water = value
            return value
        return high_water


# GENERATOR: generated below from plugin_sofar.py @ 27875b3b by
# scripts/generate_sofar_model.py — do not hand-edit past this line.


@dataclass(frozen=True, kw_only=True)
class SofarSensorDescription(SensorEntityDescription):
    """A real SensorEntityDescription, plus which Component the value comes from.

    Must subclass SensorEntityDescription (not just duck-type its fields) —
    SensorEntity reads attributes like entity_registry_visible_default and
    suggested_unit_of_measurement straight off entity_description with no
    _attr_ fallback, so a bespoke dataclass raises AttributeError on those.
    """

    component: str  # attribute name on SofarInverter, e.g. 'grid', 'pv_1_2', 'energy'


SENSOR_DESCRIPTIONS: tuple[SofarSensorDescription, ...] = (
    SofarSensorDescription(
        key="system_state",
        component="state",
        name="System State",
        device_class=SensorDeviceClass.ENUM,
        options=[
            "Waiting",
            "Checking",
            "Grid Connected",
            "Emergency Power Supply",
            "Recoverable Fault",
            "Permanent Fault",
            "Upgrading",
            "Self Charging",
        ],
    ),
    SofarSensorDescription(
        key="fault_1",
        component="state",
        name="Fault 1",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="fault_2",
        component="state",
        name="Fault 2",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="fault_3",
        component="state",
        name="Fault 3",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="fault_4",
        component="state",
        name="Fault 4",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="fault_5",
        component="state",
        name="Fault 5",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="fault_6",
        component="state",
        name="Fault 6",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="fault_7",
        component="state",
        name="Fault 7",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="fault_8",
        component="state",
        name="Fault 8",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="fault_9",
        component="state",
        name="Fault 9",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="fault_10",
        component="state",
        name="Fault 10",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="fault_11",
        component="state",
        name="Fault 11",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="fault_12",
        component="state",
        name="Fault 12",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="waiting_time",
        component="state",
        name="Waiting Time",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="inverter_temperature_1",
        component="state",
        name="Inverter Temperature 1",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="inverter_temperature_2",
        component="state",
        name="Inverter Temperature 2",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="heatsink_temperature_1",
        component="state",
        name="Heatsink Temperature 1",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="heatsink_temperature_2",
        component="state",
        name="Heatsink Temperature 2",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="module_temperature_1",
        component="state",
        name="Module Temperature 1",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="module_temperature_2",
        component="state",
        name="Module Temperature 2",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="rtc",
        component="identity",
        name="System Time",
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:clock",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="serial_number",
        component="identity",
        name="Serial Number",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="hardware_version",
        component="identity",
        name="Hardware Version",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="software_version",
        component="identity",
        name="Software Version",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="grid_frequency",
        component="grid",
        name="Grid Frequency",
        device_class=SensorDeviceClass.FREQUENCY,
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="active_power_output_total",
        component="grid",
        name="Active Power Output Total",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="reactive_power_output_total",
        component="grid",
        name="Reactive Power Output Total",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="apparent_power_output_total",
        component="grid",
        name="Apparent Power Output Total",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="active_power_pcc_total",
        component="grid",
        name="Active Power PCC Total",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="reactive_power_pcc_total",
        component="grid",
        name="Reactive Power PCC Total",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="apparent_power_pcc_total",
        component="grid",
        name="Apparent Power PCC Total",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="voltage_l1",
        component="grid",
        name="Voltage L1",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="current_output_l1",
        component="grid",
        name="Current Output L1",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="active_power_output_l1",
        component="grid",
        name="Active Power Output L1",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="reactive_power_output_l1",
        component="grid",
        name="Reactive Power Output L1",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="power_factor_output_l1",
        component="grid",
        name="Power Factor Output L1",
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="current_pcc_l1",
        component="grid",
        name="Current PCC L1",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="active_power_pcc_l1",
        component="grid",
        name="Active Power PCC L1",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="reactive_power_pcc_l1",
        component="grid",
        name="Reactive Power PCC L1",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="power_factor_pcc_l1",
        component="grid",
        name="Power Factor PCC L1",
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="voltage_l2",
        component="grid",
        name="Voltage L2",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="current_output_l2",
        component="grid",
        name="Current Output L2",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="active_power_output_l2",
        component="grid",
        name="Active Power Output L2",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="reactive_power_output_l2",
        component="grid",
        name="Reactive Power Output L2",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="power_factor_output_l2",
        component="grid",
        name="Power Factor Output L2",
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="current_pcc_l2",
        component="grid",
        name="Current PCC L2",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="active_power_pcc_l2",
        component="grid",
        name="Active Power PCC L2",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="reactive_power_pcc_l2",
        component="grid",
        name="Reactive Power PCC L2",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="power_factor_pcc_l2",
        component="grid",
        name="Power Factor PCC L2",
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="voltage_l3",
        component="grid",
        name="Voltage L3",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="current_output_l3",
        component="grid",
        name="Current Output L3",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="active_power_output_l3",
        component="grid",
        name="Active Power Output L3",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="reactive_power_output_l3",
        component="grid",
        name="Reactive Power Output L3",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="power_factor_output_l3",
        component="grid",
        name="Power Factor Output L3",
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="current_pcc_l3",
        component="grid",
        name="Current PCC L3",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="active_power_pcc_l3",
        component="grid",
        name="Active Power PCC L3",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="reactive_power_pcc_l3",
        component="grid",
        name="Reactive Power PCC L3",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="power_factor_pcc_l3",
        component="grid",
        name="Power Factor PCC L3",
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="active_power_pv_ext",
        component="grid",
        name="Active Power PV Ext",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="active_power_load_sys",
        component="grid",
        name="Active Power Load Sys",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="voltage_phase_l1n",
        component="grid",
        name="Voltage Phase L1N",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="current_output_l1n",
        component="grid",
        name="Current Output L1N",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="active_power_output_l1n",
        component="grid",
        name="Active Power Output L1N",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="current_pcc_l1n",
        component="grid",
        name="Current PCC L1N",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="active_power_pcc_l1n",
        component="grid",
        name="Active Power PCC L1N",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="voltage_phase_l2n",
        component="grid",
        name="Voltage Phase L2N",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="current_output_l2n",
        component="grid",
        name="Current Output L2N",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="active_power_output_l2n",
        component="grid",
        name="Active Power Output L2N",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="current_pcc_l2n",
        component="grid",
        name="Current PCC L2N",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="active_power_pcc_l2n",
        component="grid",
        name="Active Power PCC L2N",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="voltage_line_l1",
        component="grid",
        name="Voltage Line L1",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="voltage_line_l2",
        component="grid",
        name="Voltage Line L2",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="voltage_line_l3",
        component="grid",
        name="Voltage Line L3",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="active_power_offgrid_total",
        component="offgrid",
        name="Active Power Off-Grid Total",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="reactive_power_offgrid_total",
        component="offgrid",
        name="Reactive Power Off-Grid Total",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="apparent_power_offgrid_total",
        component="offgrid",
        name="Apparent Power Off-Grid Total",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_frequency",
        component="offgrid",
        name="Off-Grid Frequency",
        device_class=SensorDeviceClass.FREQUENCY,
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_voltage",
        component="offgrid_single_phase",
        name="Off-Grid Voltage",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="offgrid_voltage_l1",
        component="offgrid_three_phase",
        name="Off-Grid Voltage L1",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="offgrid_current_output",
        component="offgrid_single_phase",
        name="Off-Grid Current Output",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_current_output_l1",
        component="offgrid_three_phase",
        name="Off-Grid Current Output L1",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_active_power_output",
        component="offgrid_single_phase",
        name="Off-Grid Active Power Output",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_active_power_output_l1",
        component="offgrid_three_phase",
        name="Off-Grid Active Power Output L1",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_reactive_power_output",
        component="offgrid_single_phase",
        name="Off-Grid Reactive Power Output",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_reactive_power_output_l1",
        component="offgrid_three_phase",
        name="Off-Grid Reactive Power Output L1",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_apparent_power_output",
        component="offgrid_single_phase",
        name="Off-Grid Apparent Power Output",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_apparent_power_output_l1",
        component="offgrid_three_phase",
        name="Off-Grid Apparent Power Output L1",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_loadpeakratio",
        component="offgrid_single_phase",
        name="Off-Grid LoadPeakRatio",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_loadpeakratio_l1",
        component="offgrid_three_phase",
        name="Off-Grid LoadPeakRatio L1",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_voltage_l2",
        component="offgrid_three_phase",
        name="Off-Grid Voltage L2",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="offgrid_current_output_l2",
        component="offgrid_three_phase",
        name="Off-Grid Current Output L2",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_active_power_output_l2",
        component="offgrid_three_phase",
        name="Off-Grid Active Power Output L2",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_reactive_power_output_l2",
        component="offgrid_three_phase",
        name="Off-Grid Reactive Power Output L2",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_apparent_power_output_l2",
        component="offgrid_three_phase",
        name="Off-Grid Apparent Power Output L2",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_loadpeakratio_l2",
        component="offgrid_three_phase",
        name="Off-Grid LoadPeakRatio L2",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_voltage_l3",
        component="offgrid_three_phase",
        name="Off-Grid Voltage L3",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="offgrid_current_output_l3",
        component="offgrid_three_phase",
        name="Off-Grid Current Output L3",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_active_power_output_l3",
        component="offgrid_three_phase",
        name="Off-Grid Active Power Output L3",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_reactive_power_output_l3",
        component="offgrid_three_phase",
        name="Off-Grid Reactive Power Output L3",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_apparent_power_output_l3",
        component="offgrid_three_phase",
        name="Off-Grid Apparent Power Output L3",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_loadpeakratio_l3",
        component="offgrid_three_phase",
        name="Off-Grid LoadPeakRatio L3",
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement=UnitOfApparentPower.VOLT_AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_voltage_output_l1n",
        component="offgrid_three_phase",
        name="Off-Grid Voltage Output L1N",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="offgrid_current_output_l1n",
        component="offgrid_three_phase",
        name="Off-Grid Current Output L1N",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_active_power_output_l1n",
        component="offgrid_three_phase",
        name="Off-Grid Active Power Output L1N",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_voltage_output_l2n",
        component="offgrid_three_phase",
        name="Off-Grid Voltage Output L2N",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="offgrid_current_output_l2n",
        component="offgrid_three_phase",
        name="Off-Grid Current Output L2N",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="offgrid_active_power_output_l2n",
        component="offgrid_three_phase",
        name="Off-Grid Active Power Output L2N",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_voltage_1",
        component="pv_1_2",
        name="PV Voltage 1",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="pv_current_1",
        component="pv_1_2",
        name="PV Current 1",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_power_1",
        component="pv_1_2",
        name="PV Power 1",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_voltage_2",
        component="pv_1_2",
        name="PV Voltage 2",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="pv_current_2",
        component="pv_1_2",
        name="PV Current 2",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_power_2",
        component="pv_1_2",
        name="PV Power 2",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_voltage_3",
        component="pv_3",
        name="PV Voltage 3",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="pv_current_3",
        component="pv_3",
        name="PV Current 3",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_power_3",
        component="pv_3",
        name="PV Power 3",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_voltage_4",
        component="pv_4",
        name="PV Voltage 4",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="pv_current_4",
        component="pv_4",
        name="PV Current 4",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_power_4",
        component="pv_4",
        name="PV Power 4",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_voltage_5",
        component="pv_5_6",
        name="PV Voltage 5",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="pv_current_5",
        component="pv_5_6",
        name="PV Current 5",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_power_5",
        component="pv_5_6",
        name="PV Power 5",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_voltage_6",
        component="pv_5_6",
        name="PV Voltage 6",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="pv_current_6",
        component="pv_5_6",
        name="PV Current 6",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_power_6",
        component="pv_5_6",
        name="PV Power 6",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_voltage_7",
        component="pv_7_8",
        name="PV Voltage 7",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="pv_current_7",
        component="pv_7_8",
        name="PV Current 7",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_power_7",
        component="pv_7_8",
        name="PV Power 7",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_voltage_8",
        component="pv_7_8",
        name="PV Voltage 8",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="pv_current_8",
        component="pv_7_8",
        name="PV Current 8",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_power_8",
        component="pv_7_8",
        name="PV Power 8",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_voltage_9",
        component="pv_9_10",
        name="PV Voltage 9",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="pv_current_9",
        component="pv_9_10",
        name="PV Current 9",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_power_9",
        component="pv_9_10",
        name="PV Power 9",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_voltage_10",
        component="pv_9_10",
        name="PV Voltage 10",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="pv_current_10",
        component="pv_9_10",
        name="PV Current 10",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_power_10",
        component="pv_9_10",
        name="PV Power 10",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="pv_power_total",
        component="pv_1_2",
        name="PV Power Total",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SofarSensorDescription(
        key="battery_voltage_1",
        component="battery_1_2",
        name="Battery Voltage 1",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
    ),
    SofarSensorDescription(
        key="battery_current_1",
        component="battery_1_2",
        name="Battery Current 1",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="battery_power_1",
        component="battery_1_2",
        name="Battery Power 1",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="battery_temperature_1",
        component="battery_1_2",
        name="Battery Temperature 1",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="battery_capacity_1",
        component="battery_1_2",
        name="Battery Capacity 1",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SofarSensorDescription(
        key="battery_state_of_health_1",
        component="battery_1_2",
        name="Battery State of Health 1",
        native_unit_of_measurement=PERCENTAGE,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-heart",
    ),
    SofarSensorDescription(
        key="battery_charge_cycle_1",
        component="battery_1_2",
        name="Battery Charge Cycle 1",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SofarSensorDescription(
        key="battery_voltage_2",
        component="battery_1_2",
        name="Battery Voltage 2",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_current_2",
        component="battery_1_2",
        name="Battery Current 2",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="battery_power_2",
        component="battery_1_2",
        name="Battery Power 2",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="battery_temperature_2",
        component="battery_1_2",
        name="Battery Temperature 2",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_capacity_2",
        component="battery_1_2",
        name="Battery Capacity 2",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_state_of_health_2",
        component="battery_1_2",
        name="Battery State of Health 2",
        native_unit_of_measurement=PERCENTAGE,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-heart",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_charge_cycle_2",
        component="battery_1_2",
        name="Battery Charge Cycle 2",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_voltage_3",
        component="battery_3_8",
        name="Battery Voltage 3",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_current_3",
        component="battery_3_8",
        name="Battery Current 3",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="battery_power_3",
        component="battery_3_8",
        name="Battery Power 3",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="battery_temperature_3",
        component="battery_3_8",
        name="Battery Temperature 3",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_capacity_3",
        component="battery_3_8",
        name="Battery Capacity 3",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_state_of_health_3",
        component="battery_3_8",
        name="Battery State of Health 3",
        native_unit_of_measurement=PERCENTAGE,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-heart",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_charge_cycle_3",
        component="battery_3_8",
        name="Battery Charge Cycle 3",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_voltage_4",
        component="battery_3_8",
        name="Battery Voltage 4",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_current_4",
        component="battery_3_8",
        name="Battery Current 4",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="battery_power_4",
        component="battery_3_8",
        name="Battery Power 4",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="battery_temperature_4",
        component="battery_3_8",
        name="Battery Temperature 4",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_capacity_4",
        component="battery_3_8",
        name="Battery Capacity 4",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_state_of_health_4",
        component="battery_3_8",
        name="Battery State of Health 4",
        native_unit_of_measurement=PERCENTAGE,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-heart",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_charge_cycle_4",
        component="battery_3_8",
        name="Battery Charge Cycle 4",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_voltage_5",
        component="battery_3_8",
        name="Battery Voltage 5",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_current_5",
        component="battery_3_8",
        name="Battery Current 5",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="battery_power_5",
        component="battery_3_8",
        name="Battery Power 5",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="battery_temperature_5",
        component="battery_3_8",
        name="Battery Temperature 5",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_capacity_5",
        component="battery_3_8",
        name="Battery Capacity 5",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_state_of_health_5",
        component="battery_3_8",
        name="Battery State of Health 5",
        native_unit_of_measurement=PERCENTAGE,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-heart",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_charge_cycle_5",
        component="battery_3_8",
        name="Battery Charge Cycle 5",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_voltage_6",
        component="battery_3_8",
        name="Battery Voltage 6",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_current_6",
        component="battery_3_8",
        name="Battery Current 6",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="battery_power_6",
        component="battery_3_8",
        name="Battery Power 6",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="battery_temperature_6",
        component="battery_3_8",
        name="Battery Temperature 6",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_capacity_6",
        component="battery_3_8",
        name="Battery Capacity 6",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_state_of_health_6",
        component="battery_3_8",
        name="Battery State of Health 6",
        native_unit_of_measurement=PERCENTAGE,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-heart",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_charge_cycle_6",
        component="battery_3_8",
        name="Battery Charge Cycle 6",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_voltage_7",
        component="battery_3_8",
        name="Battery Voltage 7",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_current_7",
        component="battery_3_8",
        name="Battery Current 7",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="battery_power_7",
        component="battery_3_8",
        name="Battery Power 7",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="battery_temperature_7",
        component="battery_3_8",
        name="Battery Temperature 7",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_capacity_7",
        component="battery_3_8",
        name="Battery Capacity 7",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_state_of_health_7",
        component="battery_3_8",
        name="Battery State of Health 7",
        native_unit_of_measurement=PERCENTAGE,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-heart",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_charge_cycle_7",
        component="battery_3_8",
        name="Battery Charge Cycle 7",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_voltage_8",
        component="battery_3_8",
        name="Battery Voltage 8",
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_current_8",
        component="battery_3_8",
        name="Battery Current 8",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="battery_power_8",
        component="battery_3_8",
        name="Battery Power 8",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="battery_temperature_8",
        component="battery_3_8",
        name="Battery Temperature 8",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_capacity_8",
        component="battery_3_8",
        name="Battery Capacity 8",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_state_of_health_8",
        component="battery_3_8",
        name="Battery State of Health 8",
        native_unit_of_measurement=PERCENTAGE,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-heart",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_charge_cycle_8",
        component="battery_3_8",
        name="Battery Charge Cycle 8",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_power_total",
        component="battery_totals",
        name="Battery Power Total",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SofarSensorDescription(
        key="battery_capacity_total",
        component="battery_totals",
        name="Battery Capacity Total",
        device_class=SensorDeviceClass.BATTERY,
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SofarSensorDescription(
        key="battery_state_of_health_total",
        component="battery_totals",
        name="Battery State of Health Total",
        native_unit_of_measurement=PERCENTAGE,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-heart",
    ),
    SofarSensorDescription(
        key="solar_generation_today",
        component="energy",
        name="Solar Generation Today",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="solar_generation_total",
        component="energy",
        name="Solar Generation Total",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SofarSensorDescription(
        key="load_consumption_today",
        component="energy",
        name="Load Consumption Today",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="load_consumption_total",
        component="energy",
        name="Load Consumption Total",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SofarSensorDescription(
        key="import_energy_today",
        component="energy",
        name="Import Energy Today",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:home-import-outline",
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="import_energy_total",
        component="energy",
        name="Import Energy Total",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:home-import-outline",
    ),
    SofarSensorDescription(
        key="export_energy_today",
        component="energy",
        name="Export Energy Today",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:home-export-outline",
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="export_energy_total",
        component="energy",
        name="Export Energy Total",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:home-export-outline",
    ),
    SofarSensorDescription(
        key="battery_input_energy_today",
        component="battery_energy",
        name="Battery Input Energy Today",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:battery-arrow-up",
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="battery_input_energy_total",
        component="battery_energy",
        name="Battery Input Energy Total",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:battery-arrow-up",
    ),
    SofarSensorDescription(
        key="battery_output_energy_today",
        component="battery_energy",
        name="Battery Output Energy Today",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:battery-arrow-down",
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="battery_output_energy_total",
        component="battery_energy",
        name="Battery Output Energy Total",
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:battery-arrow-down",
    ),
    SofarSensorDescription(
        key="passive_eps_wait_time",
        component="eps",
        name="EPS Wait Time",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="battery_active_control",
        component="battery_active_control",
        name="Battery Active Control",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="parallel_control",
        component="parallel",
        name="Parallel Control",
    ),
    SofarSensorDescription(
        key="parallel_masterslave",
        component="parallel",
        name="Parallel Master-Salve",
        device_class=SensorDeviceClass.ENUM,
        options=["Slave", "Master"],
    ),
    SofarSensorDescription(
        key="bat_config_id",
        component="battery_config_id",
        name="BatConfig: ID",
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="bat_config_address_1",
        component="battery_config_id",
        name="BatConfig: Address 1",
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="bat_config_protocol",
        component="battery_config_id",
        name="BatConfig: Protocol",
        device_class=SensorDeviceClass.ENUM,
        options=[
            "First Flight Built In Bms Default",
            "Pie Energy Protocol Pylon",
            "First Flight Protocol General",
            "Amass",
            "Lg",
            "Alphaess",
            "Catl",
            "Weco",
            "Fronus",
            "Ems",
            "Nilar",
            "Bts 5k",
            "Move For",
        ],
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="bat_config_overvoltage_protection",
        component="battery_config_id",
        name="BatConfig: Overvoltage Protection",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="bat_config_charging_voltage",
        component="battery_config",
        name="BatConfig: Charging Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
    ),
    SofarSensorDescription(
        key="bat_config_undervoltage_protection",
        component="battery_config",
        name="BatConfig: Undervoltage Protection",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="bat_config_minimum_discharge_voltage",
        component="battery_config",
        name="BatConfig: Minimum Discharge Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="bat_config_maximum_charge_current_limit",
        component="battery_config",
        name="BatConfig: Maximum Charge Current Limit",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="bat_config_maximum_discharge_current_limit",
        component="battery_config",
        name="BatConfig: Maximum Discharge Current Limit",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
    ),
    SofarSensorDescription(
        key="bat_config_depth_of_discharge",
        component="battery_config",
        name="BatConfig: Depth of Discharge",
        native_unit_of_measurement=PERCENTAGE,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="bat_config_end_of_discharge",
        component="battery_config",
        name="BatConfig: End of Discharge",
        native_unit_of_measurement=PERCENTAGE,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="bat_config_capacity",
        component="battery_config",
        name="BatConfig: Capacity",
        native_unit_of_measurement="Ah",
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="bat_config_rated_battery_voltage",
        component="battery_config",
        name="BatConfig: Rated Battery Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="bat_config_cell_type",
        component="battery_config",
        name="BatConfig: Cell Type",
        device_class=SensorDeviceClass.ENUM,
        options=["Lead Acid", "Lithium Iron Phosphate", "Ternary", "Lithium Titanate", "Agm", "Gel", "Flooded"],
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="bat_config_eps_buffer",
        component="battery_config",
        name="BatConfig: EPS Buffer",
        native_unit_of_measurement=PERCENTAGE,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="bat_config_address_2",
        component="battery_config",
        name="BatConfig: Address 2",
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="bat_config_address_3",
        component="battery_config",
        name="BatConfig: Address 3",
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="bat_config_address_4",
        component="battery_config",
        name="BatConfig: Address 4",
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="bat_config_tempco",
        component="battery_config",
        name="BatConfig: Lead Acid Battery Temperature Compensation Factor",
        native_unit_of_measurement="mV/Cell",
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="bat_config_voltage_float",
        component="battery_config",
        name="BatConfig: Lead Acid Battery Float Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-check-outline",
        entity_registry_enabled_default=False,
    ),
    SofarSensorDescription(
        key="sync_rtc_result",
        component="rtc_sync",
        name="Update System Time Operation Result",
        device_class=SensorDeviceClass.ENUM,
        options=[
            "Successful",
            "Operation In Progress",
            "Enabled Discharging",
            "Disabled",
            "Operation Failed Controller Refused To Respond",
            "Operation Failed No Response From The Controller",
            "Operation Failed Current Function Disabled",
            "Operation Failed Parameter Access Failed",
            "Operation Failed Input Parameters Incorrect",
        ],
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
)
